/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.12.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { Coin } from "@cosmjs/amino";
import { MsgExecuteContractEncodeObject } from "@cosmjs/cosmwasm-stargate";
import { MsgExecuteContract } from "cosmjs-types/cosmwasm/wasm/v1/tx";
import { toUtf8 } from "@cosmjs/encoding";
import { InstantiateMsg, ExecuteMsg, QueryMsg, Addr, OrderSort, GetStocksResponse, Stock, GetBidByIdResponse, Bid, GetBidsResponse, GetBuyOrderByIdResponse, BuyOrder, GetBuyPriceResponse, GetMinimumBidPriceResponse, GetSellPriceResponse, GetBuyOrdersResponse, GetSaleByIdResponse, Sale, GetSalesResponse, GetSalesByUserResponse, GetSellOrderByIdResponse, SellOrder, GetShareByIdResponse, Share, GetSharesResponse, GetStockByIdResponse, GetTotalBuyVolumeResponse, GetTotalSellVolumeResponse } from "./Contract.types";
export interface ContractMsg {
  contractAddress: string;
  sender: string;
  createStock: ({
    ticker
  }: {
    ticker: string;
  }, funds_?: Coin[]) => MsgExecuteContractEncodeObject;
  startAuction: ({
    stockId
  }: {
    stockId: number;
  }, funds_?: Coin[]) => MsgExecuteContractEncodeObject;
  endAuction: ({
    stockId
  }: {
    stockId: number;
  }, funds_?: Coin[]) => MsgExecuteContractEncodeObject;
  placeBid: ({
    pricePerShare,
    shares,
    stockId
  }: {
    pricePerShare: number;
    shares: number;
    stockId: number;
  }, funds_?: Coin[]) => MsgExecuteContractEncodeObject;
  createBuyOrder: ({
    pricePerShare,
    shares,
    stockId
  }: {
    pricePerShare: number;
    shares: number;
    stockId: number;
  }, funds_?: Coin[]) => MsgExecuteContractEncodeObject;
  createSellOrder: ({
    pricePerShare,
    shares,
    stockId
  }: {
    pricePerShare: number;
    shares: number;
    stockId: number;
  }, funds_?: Coin[]) => MsgExecuteContractEncodeObject;
  cancelBuyOrder: ({
    buyOrderId
  }: {
    buyOrderId: number;
  }, funds_?: Coin[]) => MsgExecuteContractEncodeObject;
  cancelSellOrder: ({
    sellOrderId
  }: {
    sellOrderId: number;
  }, funds_?: Coin[]) => MsgExecuteContractEncodeObject;
  quickSell: ({
    pricePerShare,
    shares,
    slippage,
    stockId
  }: {
    pricePerShare: number;
    shares: number;
    slippage: number;
    stockId: number;
  }, funds_?: Coin[]) => MsgExecuteContractEncodeObject;
  quickBuy: ({
    shares,
    slippage,
    stockId
  }: {
    shares: number;
    slippage: number;
    stockId: number;
  }, funds_?: Coin[]) => MsgExecuteContractEncodeObject;
}
export class ContractMsgComposer implements ContractMsg {
  sender: string;
  contractAddress: string;
  constructor(sender: string, contractAddress: string) {
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.createStock = this.createStock.bind(this);
    this.startAuction = this.startAuction.bind(this);
    this.endAuction = this.endAuction.bind(this);
    this.placeBid = this.placeBid.bind(this);
    this.createBuyOrder = this.createBuyOrder.bind(this);
    this.createSellOrder = this.createSellOrder.bind(this);
    this.cancelBuyOrder = this.cancelBuyOrder.bind(this);
    this.cancelSellOrder = this.cancelSellOrder.bind(this);
    this.quickSell = this.quickSell.bind(this);
    this.quickBuy = this.quickBuy.bind(this);
  }
  createStock = ({
    ticker
  }: {
    ticker: string;
  }, funds_?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          create_stock: {
            ticker
          }
        })),
        funds: funds_
      })
    };
  };
  startAuction = ({
    stockId
  }: {
    stockId: number;
  }, funds_?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          start_auction: {
            stock_id: stockId
          }
        })),
        funds: funds_
      })
    };
  };
  endAuction = ({
    stockId
  }: {
    stockId: number;
  }, funds_?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          end_auction: {
            stock_id: stockId
          }
        })),
        funds: funds_
      })
    };
  };
  placeBid = ({
    pricePerShare,
    shares,
    stockId
  }: {
    pricePerShare: number;
    shares: number;
    stockId: number;
  }, funds_?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          place_bid: {
            price_per_share: pricePerShare,
            shares,
            stock_id: stockId
          }
        })),
        funds: funds_
      })
    };
  };
  createBuyOrder = ({
    pricePerShare,
    shares,
    stockId
  }: {
    pricePerShare: number;
    shares: number;
    stockId: number;
  }, funds_?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          create_buy_order: {
            price_per_share: pricePerShare,
            shares,
            stock_id: stockId
          }
        })),
        funds: funds_
      })
    };
  };
  createSellOrder = ({
    pricePerShare,
    shares,
    stockId
  }: {
    pricePerShare: number;
    shares: number;
    stockId: number;
  }, funds_?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          create_sell_order: {
            price_per_share: pricePerShare,
            shares,
            stock_id: stockId
          }
        })),
        funds: funds_
      })
    };
  };
  cancelBuyOrder = ({
    buyOrderId
  }: {
    buyOrderId: number;
  }, funds_?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          cancel_buy_order: {
            buy_order_id: buyOrderId
          }
        })),
        funds: funds_
      })
    };
  };
  cancelSellOrder = ({
    sellOrderId
  }: {
    sellOrderId: number;
  }, funds_?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          cancel_sell_order: {
            sell_order_id: sellOrderId
          }
        })),
        funds: funds_
      })
    };
  };
  quickSell = ({
    pricePerShare,
    shares,
    slippage,
    stockId
  }: {
    pricePerShare: number;
    shares: number;
    slippage: number;
    stockId: number;
  }, funds_?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          quick_sell: {
            price_per_share: pricePerShare,
            shares,
            slippage,
            stock_id: stockId
          }
        })),
        funds: funds_
      })
    };
  };
  quickBuy = ({
    shares,
    slippage,
    stockId
  }: {
    shares: number;
    slippage: number;
    stockId: number;
  }, funds_?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          quick_buy: {
            shares,
            slippage,
            stock_id: stockId
          }
        })),
        funds: funds_
      })
    };
  };
}