/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.12.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./Contract.types";
import * as _1 from "./Contract.client";
import * as _2 from "./Contract.message-composer";
export namespace contracts {
  export const Contract = {
    ..._0,
    ..._1,
    ..._2
  };
}